### ISSUE TITLE
UnicodeDecode Errors

### ISSUE THREAD

**Issue by robweber** [romanvm/kodi.six#3]
Two different users have report errors being thrown in one of [my addons](https://github.com/robweber/script.grab.fanart) that uses kodi-six. In both cases the error is thrown by the kodi-six library: 

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 170654: invalid continuation byte
```

This is happening on an ```xbmc.executeJSONRPC()``` method call for both. I'm guessing the JSON result contains some characters that are causing this issue. Below are the log files given to me with the errors. 

[Kodi 18.4 - Windows](https://paste.kodi.tv/acoqakafes.kodi) (line 1242)
[Kodi 18.3 - Linux](https://paste.kodi.tv/yowehuyisu.kodi) (line 254)

**Comment by romanvm** [comment]
Honestly, I'm not sure what to do with it. An obvious fix would be to ignore invalid bytes, but the same will probably happen in Python 3 only on deeper level because in Py3-based Kodi API std::string return values are always decoded to Py3's Unicode `str`, so the fix won't really solve anything in the long term.

**Comment by robweber** [comment]
I wish I knew more about the underlying text that was causing this error. The calls are to GetArtists and GetMovies. Some searching I did on the error seems to point towards an acute mark from a latin-1 encoding causing the problem. Most likely in the title or artist name in one of the responses. 

I'm not super well versed in any of this but from what I gather the \xe9 in UTF-8 is invalid. I see your point that in Py2 you could choose to ignore the error but in Py3 it's going to cause problems anyway. Probably not a real good solution as you've stated. A bit hard to explain to a user that Kodi's JSON server is returning text that Kodi's python libraries can't read but I guess that's the case here.

**Comment by romanvm** [comment]
Yes, "high" characters with codes > 127 in 8-bit fixed-lengths national encodings like latin-1 or cp1251 cannot be decoded by UTF-8 decoder. The problem is that Kodi stores text as byte sequences without enforcing any specific encoding (although UTF-8 is assumed by default). It did not cause big problems so far because Py2 `str` is a byte sequence as well, so no decoding is done when receiving text data from Kodi API. However, in Py3 `str` object stores text as Unicode code points (with UTF-32 encoding used for internal storage) and UTF-8 is used for implicit conversions from bytes to text and vice versa. So I'm afraid it won't be the last problem in Py3-based Kodi API when text data is passed to/from C++ level.

**Comment by robweber** [comment]
Thank you for the more in depth explanation, I appreciate it. I'll close this out as I really don't think there is much that can be done. I'll report back to the users that initially told me they were having issues.

**Comment by romanvm** [comment]
I did a bit of digging on how code generation for Kodi Python modules works and I guess I can fix this error in Kodi itself (Python 3 build). So I will update kodi-six accordingly.

**Comment by robweber** [comment]
That is great, thank you. So for python2 builds they'll continue to see this but as we migrate to python3 things will straighten out? Just want to make sure I communicate this correctly as issues crop up.

**Comment by romanvm** [comment]
As I said, Py2-based Kodi API is not affected by this because strings are returned as bytes. It will be fixed both in kodi-six and Py3-based Kodi API.
Technically, it is not a real fix. Problematic bytes will be replaced with so called "Unicode replacement characters", so the resulting text won't look good, but at lease there wont be any errors.

**Comment by robweber** [comment]
Ok, the only reason I ask is because the error cases I'm getting are from Kodi 18 with Python 2. I think the issue in those cases is that kodi-six is trying to convert the strings for python 2/3 compatibility in handling. Appreciate your efforts on this.
